# Generated by Django 5.1.6 on 2025-02-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('react', 'React'), ('django', 'Django'), ('vue', 'Vue')], default='react', max_length=50),
        ),
    ]
